### ISSUE TITLE
Library making http requests, without possibility to disabling it

### ISSUE THREAD

**Issue by liveforeverx** [lau/tzdata#11]
Library doing some http checks, I think that it is not good in all environments (for example because of security reasons) to make some wild http requests in a library, which doesn't seem to need to do it (it is not an API to extern data).

Would be nice to add some configuration option, like: `check_new_releases: true | false` or outsource the supervisor for release updates, that if somebody really want to update it regular, should release_updater in its own supervisor tree. What do you think about it?

**Comment by lau** [comment]
See the "Automatic data updates" section of the readme on how to disable it.

**Comment by lau** [comment]
It is a very important feature. A lot of organizations fail to be up to date because they rely on manual or processes to do it. Or they don't have any process at all for being up to date. That means that the tzdata eventually become out of date and produce incorrect results. So the idea is to have the computer do it. If the app has internet access I would recommend to leave the feature enabled.

**Comment by liveforeverx** [comment]
Thanks! RTFM for me.

**Comment by thmzlt** [comment]
Would it be possible to make the hackney dependency optional for when not using the automatic data updates feature?

**Comment by lau** [comment]
@thmzlt I want the automatic update feature to be on by default. I don't think that is compatible with making hackney an optional dependency. With the way hex works. If hex changes/has changed and both can be possible, let me know.

I'm interested: how are you keeping the tzdata up to date since you are not using the automatic data updates?

**Comment by thmzlt** [comment]
> how are you keeping the tzdata up to date since you are not using the automatic data updates?

I am not. I'm using a library for formatting/parsing timestamps and it depends on tzdata (unfortunately most of the options for this task also depend on tzdata).

But I'd answer to your question with manually bumping the package version on each tzdata update. Obviously this is incompatible with the automatic update feature, so there are no expectations from my part. If you are interested in revisiting the merits of the feature, I can chime in.

**Comment by lau** [comment]
If you are using [Calendar](https://github.com/lau/calendar) you can specify tzdata ~> 0.1.201601
Then there is no hackney dependency nor any autoupdating.

**Comment by thmzlt** [comment]
Thank you.

**Comment by liveforeverx** [comment]
Hi! Another question, is it possible to disable initial http request? Probably I need to package `tzdata` somehow. Because otherwise it always crash without internet access, and my application is impossible to start.

**Comment by lau** [comment]
Hi @liveforeverx What is the problem? In the readme you can see how to disable auto updates. Then the .ets file that ships with Tzdata will be used. Or whichever file is in the dir specified in the config. See the part "Data directory and releases" in the readme.
