### ISSUE TITLE
tzdata_release_updater runs during compilation

### ISSUE THREAD

**Issue by alco** [lau/tzdata#16]
I got this error after cleaning my deps and running `mix deps.get` and then `iex -S mix`:

```
18:16:19.924 [error] Task #PID<0.786.0> started from :tzdata_release_updater terminating
** (File.Error) could not stream priv/tmp_downloads/302817//pacificnew: no such file or directory
    (elixir) lib/file/stream.ex:77: anonymous fn/2 in Enumerable.File.Stream.reduce/3
    (elixir) lib/stream.ex:1084: anonymous fn/5 in Stream.resource/3
    (elixir) lib/stream.ex:1247: Enumerable.Stream.do_each/4
    (elixir) lib/enum.ex:1477: Enum.reduce/3
    (elixir) lib/enum.ex:2248: Enum.to_list/1
    (tzdata) lib/tzdata/parser.ex:16: Tzdata.Parser.process_file/1
    (tzdata) lib/tzdata/basic_data_map.ex:8: anonymous fn/2 in Tzdata.BasicDataMap.from_files_in_dir/1
    (elixir) lib/enum.ex:1088: Enum."-map/2-lists^map/1-0-"/2
Function: #Function<0.19695994/0 in Tzdata.ReleaseUpdater.init/1>
    Args: []
```

This was surprising and I don't think it is appropriate to run the updater during the compilation step. It should only ever run when the main app is running.

This is version 0.5.2 of tzdata.

**Comment by lau** [comment]
The updater runs when tzdata runs. Isn't it mix that decides to run tzdata? Or maybe you are using Timex? If I remember correctly, at least one version of Timex runs Tzdata during compilation - I don't know if it still does. In that case, it is a Timex issue. It is a bad idea to read any Tzdata during compilation because they can change during runtime.

BTW I would update to the newest version: 0.5.6.

**Comment by alco** [comment]
You're right, this is an issue with Timex: https://github.com/bitwalker/timex/pull/123.
