### ISSUE TITLE
Function to list possible offsets for a time zone

### ISSUE THREAD

**Issue by mathieuprog** [lau/tzdata#94]
Most time zone pickers (most oftenly a `<select>` field) on the web show an offset with the time zone name; and time zones are ordered by offset (see pickers for Windows, Android, Google Calendar, ...).

Currently, I don't see any easy way to get the possible offsets for a time zone.
E.g. for Belgium it would return a list of two elements, +01:00 and +02:00.

Would it be possible to add such feature?

See also discussion on Elixir Forum:
https://elixirforum.com/t/list-of-time-zones-in-select-element/28532

**Comment by lau** [comment]
Hi Mathieu,

I think this is something that someone could make with a separate package. Maybe one that depends on Tzdata.

Personally I am not a big fan of showing the +01:00 etc. in a drop down menu. In short because it is something that can change, could be misleading and is not really necessary.

- Lau
